name: python-38

on:
  push:
    branches:
      - master
  schedule:
    - cron: "2 * * * *"

jobs:
  sync:
    uses: ./.github/workflows/sync.yml
    with:
      version: "3.8"
      tx_project: "python-38"
    secrets: inherit