name: python-311

on:
  push:
    branches:
      - master
  schedule:
    - cron: "38 * * * *"

jobs:
  sync:
    uses: ./.github/workflows/sync.yml
    with:
      version: "3.11"
      tx_project: "python-311"
    secrets: inherit
    
